#ifndef CHATCLIENTCORE_GLOBAL_H
#define CHATCLIENTCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHATCLIENTCORE_LIBRARY)
#  define CHATCLIENTCORE_EXPORT Q_DECL_EXPORT
#else
#  define CHATCLIENTCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // CHATCLIENTCORE_GLOBAL_H
